name: Handle issues
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Detalhes do evento
              run: echo "${{toJSON(github.event)}}"
              
#Issue é como se fosse um comentario ou uma sugestao no repositorio do código!